# name: "Label PRs from globs"
# on:
#   schedule:
#   - cron: "0 * * * *"

# jobs:
#   execute:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: jpmcb/prow-github-actions@v1.1.1
#         with:
#           jobs: 'pr-labeler'
#           github-token: "${{ secrets.GITHUB_TOKEN }}"

name: Prow / Pull Request Labeler
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
